### ISSUE TITLE
Compilation error.

### ISSUE THREAD

**Issue by Vadykash** [vozbu/libslave#12]
I have compilation error at this place:

Slave.cpp: In member function ‘void {anonymous}::raii_mysql_connector::connect(bool)’:
Slave.cpp:430:110: error: ‘struct slave::MasterInfo’ has no member named ‘mysql_port’
             SL_LOG_INFO(log, "Successfully connected to " << sConnOptions.mysql_host << ":" << m_master_info.mysql_port);

I have checked MasterInfo struct and didn't see field mysql_port.
All mysql connection related fields are moved into conn_options? isn't it?

(it field  are used  in old version, if I'm not mistaken)

**Comment by vozbu** [comment]
Yes, you are right. I'll fix it or you can create a pull-request.
